using System;
using System.Collections.Generic;
using System.Text;

namespace Application.Entity.Entities.CandidateModule
{
    public class CandidateProfile
    {
        public CandidateProfileFormMasterData CandidateProfileData { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
    }

    public class CampusCandidateProfile
    {
        public CampusCandidateProfileFormMasterData CandidateProfileData { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
    }

    public class CandidateProfileFormData
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public String CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public String CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
        public bool MRFRealtives { get; set; }
        public bool TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        public bool PreInterViewMRF { get; set; }
        public bool CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
        public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
        public bool IsInternalRef { get; set; }
        public string InternalRefName { get; set; }
    }


    public class CampusCandidateProfileFormData
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public String CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public String CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
        public bool MRFRealtives { get; set; }
        public bool TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        public bool PreInterViewMRF { get; set; }
        public bool CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
        public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool CampusPlacement { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
    }
    public class CandidateProfileCopy
    {
        public CandidateProfileFormMasterDataCopy CandidateProfileData { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
    }
    public class CandidateProfileFormDataCopy
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public String CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public String CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
       // public bool MRFRealtives { get; set; }
        public string MRFRealtives { get; set; }
       // public bool TyreCompanyRealtionShip { get; set; }
        public string TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        //public bool PreInterViewMRF { get; set; }
        public string PreInterViewMRF { get; set; }
       //public bool CriminalCase { get; set; }
       public string CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
       // public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
        public string Htmlfilepath { get; set; }
        public bool IsInternalRef { get; set; }
        public string InternalRefName { get; set; }
    }

    public class CampusCandidateProfileFormDataCopy
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public String CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public String CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
        // public bool MRFRealtives { get; set; }
        public string MRFRealtives { get; set; }
        // public bool TyreCompanyRealtionShip { get; set; }
        public string TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        //public bool PreInterViewMRF { get; set; }
        public string PreInterViewMRF { get; set; }
        //public bool CriminalCase { get; set; }
        public string CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
        // public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }

        public bool Campusplacement { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
        public string Htmlfilepath { get; set; }
    }

    public class CampusCandidateProfileCopy
    {
        public CampusCandidateProfileFormMasterDataCopy CandidateProfileData { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
    }
    public class CandidateProfileFormDataCopyFOrCampus
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public String CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public String CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
        // public bool MRFRealtives { get; set; }
        public string MRFRealtives { get; set; }
        // public bool TyreCompanyRealtionShip { get; set; }
        public string TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        //public bool PreInterViewMRF { get; set; }
        public string PreInterViewMRF { get; set; }
        //public bool CriminalCase { get; set; }
        public string CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
        // public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public bool CampusPlacement { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public List<FamilyBackgound> FamilyBackGroundDetails { get; set; }
        public List<MRFRelationShip> MRFRelationShipDetails { get; set; }
        public List<TyreCompanyRelation> TyreCompanyRelationShipDetails { get; set; }
        public List<Academic> AcademicDetails { get; set; }
        public List<Certification> CertificationDetails { get; set; }
        public List<Membership> MembershipDetails { get; set; }
        public List<ExtraCarricularActivities> ExtraCarricularActivitiesDetails { get; set; }
        public List<LanguageKnown> LanguageKnownDetails { get; set; }
        public List<PeviousAssignment> PeviousAssignmentDetails { get; set; }
        public List<MRFPreInterview> MRFPreInterviewDetails { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
        public string Htmlfilepath { get; set; }
    }
    public class FamilyBackgound
    {
        public long CandidateProfileId { get; set; }
        public int FamilyBackgoundLineId { get; set; }
        public long FamilyRelationShip { get; set; }
        public string FamilyRelationShipName { get; set; }
        public string FamilyName { get; set; }
        public string FamilyDOB { get; set; }
        public int Education { get; set; }
        public string EducationName { get; set; }
        public int Occupation { get; set; }
        public string OccupationName { get; set; }
        public string FamilyOrganisation { get; set; }
    }

    public class MRFRelationShip
    {
        public long CandidateProfileId { get; set; }
        public int MRFRelationShipLineId { get; set; }
        public string RelativeName { get; set; }
        public string RelativeEmployeeId { get; set; }
        public string RelativeDesignation { get; set; }
        public int RelativeRelationShip { get; set; }
        public string RelativeRelationShipName { get; set; }
    }

    public class TyreCompanyRelation
    {
        public long CandidateProfileId { get; set; }
        public int TyreCompanyRelationLineId { get; set; }
        public string TyreRelativeName { get; set; }
        public string TyreRelativeDesignation { get; set; }
        public int TyreRelativeRelationShip { get; set; }
        public string TyreRelativeRelationShipName { get; set; }
        public string TyreRelativeCompanyName { get; set; }
    }

    public class Academic
    {
        public long CandidateProfileId { get; set; }
        public int AcademicLineId { get; set; }
        public int Qualification { get; set; }
        public string QualificationName { get; set; }
        public int Course { get; set; }
        public string CourseName { get; set; }
        public string CourseRemarks { get; set; }
        public string Specalization { get; set; }
        public string Instutation { get; set; }
        public string AcademicAddress { get; set; }
        public int University { get; set; }
        public string UniversityName { get; set; }
        public string OtherUniversityName { get; set; }
        public string AcademicDurationFrom { get; set; }
        public string AcademicDurationTo { get; set; }
        public int CourseType { get; set; }
        public string CourseTypeName { get; set; }
        public string Subjects { get; set; }
        public int MonthOfPassing { get; set; }
        public int YearOfPassing { get; set; }
        public int Grade { get; set; }
        public string GradeName { get; set; }
        public decimal Marks { get; set; }
        public string MonthNameOfPassing { get; set; }

    }

    public class Certification
    {
        public long CandidateProfileId { get; set; }
        public int CertificationLineId { get; set; }
        public string CertificationOrganisation { get; set; }
        public string CertificationNatureofTraining { get; set; }
        public string CertificationDurationFrom { get; set; }
        public string CertificationDurationTo { get; set; }

    }

    public class Membership
    {
        public long CandidateProfileId { get; set; }
        public int MembershipLineId { get; set; }
        public string Institution { get; set; }
        public string ClassofMemberShip { get; set; }
        public string MembershipFrom { get; set; }

    }
    public class ExtraCarricularActivities
    {
        public long CandidateProfileId { get; set; }
        public int ExtraCarricularActivitiesLineId { get; set; }
        public string NatureofActivities { get; set; }
        public string LevelofAchivement { get; set; }

    }
    public class LanguageKnown
    {
        public long CandidateProfileId { get; set; }
        public int LanguageKnownLineId { get; set; }
        public int MotherTongue { get; set; }
        public string MotherTongueName { get; set; }
        public bool Read { get; set; }
        public bool Write { get; set; }
        public bool Speak { get; set; }

    }

    public class PeviousAssignment
    {
        public long CandidateProfileId { get; set; }
        public int PeviousAssignmentLineId { get; set; }
        public string PeviousAssignmentFrom { get; set; }
        public string PeviousAssignmentTo { get; set; }
        public string PeviousAssignmentOrganisation { get; set; }
        public string PeviousAssignmentAddress { get; set; }
        public string PeviousAssignmentPosition { get; set; }
        public string PeviousAssignmentDescriptionofWork { get; set; }
        public decimal PeviousAssignmentCTC { get; set; }

    }
    public class MRFPreInterview
    {
        public long CandidateProfileId { get; set; }
        public int MRFPreInterviewLineId { get; set; }
        public int Position { get; set; }
        public string PositionName { get; set; }
        public string InterviewDate { get; set; }

    }

    public class CandidateProfileFormMasterData
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public string CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public string CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
        public bool MRFRealtives { get; set; }
        public bool TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        public bool PreInterViewMRF { get; set; }
        public bool CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
        public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
        public bool IsInternalRef { get; set; }
        public string InternalRefName { get; set; }
        //public int FamilyBackgoundCandidateProfileId { get; set; }
        //public int FamilyBackgoundLineId { get; set; }
        //public long FamilyRelationShip { get; set; }
        //public string FamilyName { get; set; }
        //public string FamilyDOB { get; set; }
        //public int Education { get; set; }
        //public int Occupation { get; set; }
        //public string FamilyOrganisation { get; set; }
        //public int MRFRelationShipCandidateProfileId { get; set; }
        //public int MRFRelationShipLineId { get; set; }
        //public string RelativeName { get; set; }
        //public string RelativeEmployeeId { get; set; }
        //public string RelativeDesignation { get; set; }
        //public int RelativeRelationShip { get; set; }
        //public int TyreCompanyRelationCandidateProfileId { get; set; }
        //public int TyreCompanyRelationLineId { get; set; }
        //public string TyreRelativeName { get; set; }
        //public string TyreRelativeDesignation { get; set; }
        //public int TyreRelativeRelationShip { get; set; }
        //public int AcademicCandidateProfileId { get; set; }
        //public int AcademicLineId { get; set; }
        //public int Qualification { get; set; }
        //public int Course { get; set; }
        //public string Specalization { get; set; }
        //public string Instutation { get; set; }
        //public string AcademicAddress { get; set; }
        //public int University { get; set; }
        //public string AcademicDurationFrom { get; set; }
        //public string AcademicDurationTo { get; set; }
        //public int CourseType { get; set; }
        //public string Subjects { get; set; }
        //public int MonthOfPassing { get; set; }
        //public int YearOfPassing { get; set; }
        //public int Grade { get; set; }
        //public decimal Marks { get; set; }
        //public int CertificationCandidateProfileId { get; set; }
        //public int CertificationLineId { get; set; }
        //public string CertificationOrganisation { get; set; }
        //public string CertificationNatureofTraining { get; set; }
        //public string CertificationDurationFrom { get; set; }
        //public string CertificationDurationTo { get; set; }
        //public int MembershipCandidateProfileId { get; set; }
        //public int MembershipLineId { get; set; }
        //public string Institution { get; set; }
        //public string ClassofMemberShip { get; set; }
        //public string MembershipFrom { get; set; }
        //public int ExtraCarricularActivitiesCandidateProfileId { get; set; }
        //public int ExtraCarricularActivitiesLineId { get; set; }
        //public string NatureofActivities { get; set; }
        //public string LevelofAchivement { get; set; }
        //public int LanguageKnownCandidateProfileId { get; set; }
        //public int LanguageKnownLineId { get; set; }
        //public string MotherTongue { get; set; }
        //public string Read { get; set; }
        //public string Write { get; set; }
        //public string Speak { get; set; }
        //public int PeviousAssignmentCandidateProfileId { get; set; }
        //public int PeviousAssignmentLineId { get; set; }
        //public string PeviousAssignmentFrom { get; set; }
        //public string PeviousAssignmentTo { get; set; }
        //public string PeviousAssignmentOrganisation { get; set; }
        //public string PeviousAssignmentAddress { get; set; }
        //public string PeviousAssignmentPosition { get; set; }
        //public string PeviousAssignmentDescriptionofWork { get; set; }
        //public decimal PeviousAssignmentCTC { get; set; }
        //public int MRFPreInterviewCandidateProfileId { get; set; }
        //public int MRFPreInterviewLineId { get; set; }
        //public int Position { get; set; }
        //public string Date { get; set; }
    }

    public class CampusCandidateProfileFormMasterData
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public string CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public string CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
        public bool MRFRealtives { get; set; }
        public bool TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        public bool PreInterViewMRF { get; set; }
        public bool CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
        public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool CampusPlacement { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
        //public int FamilyBackgoundCandidateProfileId { get; set; }
        //public int FamilyBackgoundLineId { get; set; }
        //public long FamilyRelationShip { get; set; }
        //public string FamilyName { get; set; }
        //public string FamilyDOB { get; set; }
        //public int Education { get; set; }
        //public int Occupation { get; set; }
        //public string FamilyOrganisation { get; set; }
        //public int MRFRelationShipCandidateProfileId { get; set; }
        //public int MRFRelationShipLineId { get; set; }
        //public string RelativeName { get; set; }
        //public string RelativeEmployeeId { get; set; }
        //public string RelativeDesignation { get; set; }
        //public int RelativeRelationShip { get; set; }
        //public int TyreCompanyRelationCandidateProfileId { get; set; }
        //public int TyreCompanyRelationLineId { get; set; }
        //public string TyreRelativeName { get; set; }
        //public string TyreRelativeDesignation { get; set; }
        //public int TyreRelativeRelationShip { get; set; }
        //public int AcademicCandidateProfileId { get; set; }
        //public int AcademicLineId { get; set; }
        //public int Qualification { get; set; }
        //public int Course { get; set; }
        //public string Specalization { get; set; }
        //public string Instutation { get; set; }
        //public string AcademicAddress { get; set; }
        //public int University { get; set; }
        //public string AcademicDurationFrom { get; set; }
        //public string AcademicDurationTo { get; set; }
        //public int CourseType { get; set; }
        //public string Subjects { get; set; }
        //public int MonthOfPassing { get; set; }
        //public int YearOfPassing { get; set; }
        //public int Grade { get; set; }
        //public decimal Marks { get; set; }
        //public int CertificationCandidateProfileId { get; set; }
        //public int CertificationLineId { get; set; }
        //public string CertificationOrganisation { get; set; }
        //public string CertificationNatureofTraining { get; set; }
        //public string CertificationDurationFrom { get; set; }
        //public string CertificationDurationTo { get; set; }
        //public int MembershipCandidateProfileId { get; set; }
        //public int MembershipLineId { get; set; }
        //public string Institution { get; set; }
        //public string ClassofMemberShip { get; set; }
        //public string MembershipFrom { get; set; }
        //public int ExtraCarricularActivitiesCandidateProfileId { get; set; }
        //public int ExtraCarricularActivitiesLineId { get; set; }
        //public string NatureofActivities { get; set; }
        //public string LevelofAchivement { get; set; }
        //public int LanguageKnownCandidateProfileId { get; set; }
        //public int LanguageKnownLineId { get; set; }
        //public string MotherTongue { get; set; }
        //public string Read { get; set; }
        //public string Write { get; set; }
        //public string Speak { get; set; }
        //public int PeviousAssignmentCandidateProfileId { get; set; }
        //public int PeviousAssignmentLineId { get; set; }
        //public string PeviousAssignmentFrom { get; set; }
        //public string PeviousAssignmentTo { get; set; }
        //public string PeviousAssignmentOrganisation { get; set; }
        //public string PeviousAssignmentAddress { get; set; }
        //public string PeviousAssignmentPosition { get; set; }
        //public string PeviousAssignmentDescriptionofWork { get; set; }
        //public decimal PeviousAssignmentCTC { get; set; }
        //public int MRFPreInterviewCandidateProfileId { get; set; }
        //public int MRFPreInterviewLineId { get; set; }
        //public int Position { get; set; }
        //public string Date { get; set; }
    }
    public class CandidateProfileFormMasterDataCopy
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public string CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public string CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
       // public bool MRFRealtives { get; set; }
        public string MRFRealtives { get; set; }
       // public bool TyreCompanyRealtionShip { get; set; }
        public string TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        //public bool PreInterViewMRF { get; set; }
        public string PreInterViewMRF { get; set; }
         // public bool CriminalCase { get; set; }
        public string CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
       // public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }
        public bool IsInternalRef { get; set; }
        public string InternalRefName { get; set; }

    }

    public class CampusCandidateProfileFormMasterDataCopy
    {
        public long CandidateProfileId { get; set; }
        public long CandidateId { get; set; }
        public long RequisitionDetailId { get; set; }
        public string FullName { get; set; }
        //public int? CandiadatePhoto1 { get; set; }
        public string CandiadatePhoto { get; set; }
        public string PositionAppliedFor { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string CommunicationAddress { get; set; }
        public int CommunicationStateId { get; set; }
        public string CommunicationStateName { get; set; }
        public int CommunicationCountryId { get; set; }
        public string CommunicationCountryName { get; set; }
        public string CommunicationPin { get; set; }
        public string CommunicationPhoneNo { get; set; }
        public string CommunicationAlternativeContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermanentAddress { get; set; }
        public int PermanentStateId { get; set; }
        public string PermanentStateName { get; set; }
        public int PermanentCountryId { get; set; }
        public string PermanentCountryName { get; set; }
        public string PermanentPin { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentHomeTown { get; set; }
        public int PermanentNativeStateId { get; set; }
        public string PermanentNativeStateName { get; set; }
        public string AadharNo { get; set; }
        public string UANNO { get; set; }
        public string PANNo { get; set; }
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
        public int ReligionId { get; set; }
        public string ReligionName { get; set; }
        public int CasteId { get; set; }
        public string CasteName { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public int BloodGroupId { get; set; }
        public string BloodGroupName { get; set; }
        public bool EyeSightCorrected { get; set; }
        public string EyeSightRight { get; set; }
        public string EyeSightLeft { get; set; }
        public bool CronicMajorIllness { get; set; }
        public string CronicMajorIllnessDetails { get; set; }
        public bool HandiCap { get; set; }
        public string HandiCapDetails { get; set; }
        public string IdentificationMarks1 { get; set; }
        public string IdentificationMarks2 { get; set; }
        // public bool MRFRealtives { get; set; }
        public string MRFRealtives { get; set; }
        // public bool TyreCompanyRealtionShip { get; set; }
        public string TyreCompanyRealtionShip { get; set; }
        public string ReasonforGap { get; set; }
        public string DetailsofPublication { get; set; }
        public string PreOrganisationName { get; set; }
        public string PreOrganisationAddress { get; set; }
        public decimal PreOrganisationTurnOver { get; set; }
        public string PreOrganisationMainProduct { get; set; }
        public string PreOrganisationJoinedas { get; set; }
        public string PreOrganisationJoinDate { get; set; }
        public string PreOrganisationPresentPosition { get; set; }
        public string PreOrganisationPresentPositionDate { get; set; }
        public string PreOrganisationGap { get; set; }
        public decimal PreOrganisationBasic { get; set; }
        public decimal PreOrganisationHRA { get; set; }
        public decimal PreOrganisationOtherAllowances { get; set; }
        public decimal PreOrganisationAnualComponents { get; set; }
        public decimal PreOrganisationVariablePay { get; set; }
        public decimal PreOrganisationBenefits { get; set; }
        public decimal PreOrganisationRetrial { get; set; }
        public decimal PreOrganisationOthers { get; set; }
        public decimal PreOrganisationTotalCTC { get; set; }
        public string PreviousAssignmentGap { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Position { get; set; }
        public string Ref1Organisation { get; set; }
        public string Ref1Location { get; set; }
        public string Ref1ContactNo { get; set; }
        public string Ref1EmailId { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Position { get; set; }
        public string Ref2Organisation { get; set; }
        public string Ref2Location { get; set; }
        public string Ref2ContactNo { get; set; }
        public string Ref2EmailId { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Position { get; set; }
        public string Ref3Organisation { get; set; }
        public string Ref3Location { get; set; }
        public string Ref3ContactNo { get; set; }
        public string Ref3EmailId { get; set; }
        //public bool PreInterViewMRF { get; set; }
        public string PreInterViewMRF { get; set; }
        // public bool CriminalCase { get; set; }
        public string CriminalCase { get; set; }
        public string CriminalCaseDetails { get; set; }
        // public bool PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiry { get; set; }
        public string PreviousEmployemntEnquiryDetails { get; set; }
        public string AdditionoalDetails { get; set; }
        public bool JobPortal { get; set; }
        public bool CampusPlacement { get; set; }
        public bool LinkedIn { get; set; }
        public bool CareerSite { get; set; }
        public bool PaperAdvertisement { get; set; }
        public bool EmployeeReferal { get; set; }
        public string RefNameofEmployee { get; set; }
        public string RefEmployeeId { get; set; }
        public string RefEmployeeDesignation { get; set; }
        public string RefEmployeeLocation { get; set; }
        public string RefEmployeeFunction { get; set; }
        public string RefEmployeeKnowing { get; set; }
        public bool ConsultantApplicable { get; set; }
        public int Consultant { get; set; }
        public string OtherSource { get; set; }
        public decimal expectedCTC { get; set; }
        public int joiningDaysRequired { get; set; }
        public string joiningComments { get; set; }
        public string SignatureDate { get; set; }
        public string SignaturePlace { get; set; }
        public string Signature { get; set; }
        public string CreatedBy { get; set; }
        public int SubmitStatus { get; set; }
        public bool IsEnabled { get; set; }
        public string GenderName { get; set; }
        public string ConsultantName { get; set; }

    }
    public class SearchCandidateProfile
    {
        public long? CandidateProfileId { get; set; }
        public long? CandidateId { get; set; }
        public long? RequisitionDetailId { get; set; }
    }

    public class CandidateProfileAStatusFormData
    {
        public long CandidateId { get; set; }
        public bool IsEnabled { get; set; }
        public long CreatedBy { get; set; }
    }


}



